name  : Build on PR


on : pull_request :
braches :
   - master 


   jobs :
     build :
         runs-on : ubuntu-latest
         steps :
          -uses :actions/checkout@v3
          -name :Use Node.js
          uses : actions/step-node@v3
          with .node-version :'20'

          - name : install Dependencies
            run: npm install

          -name : Run Build
           run: npm run build  